### ISSUE TITLE
无法获取token：连接至同一局域网，微信扫二维码提示无法连接到此网络，浏览器打开此网页就能显示同意青春上海但浏览器打开没用

### ISSUE THREAD

**Issue by FlanneryLong** [vvbbnn00/qndxxAutoStudy#1]
RT

**Comment by vvbbnn00** [comment]
你好，请检查一下打开页面时的IP地址是否为`内网地址`(例如`192.168.1.2`)而不是`127.0.0.1`

**Comment by FlanneryLong** [comment]
> 你好，请检查一下打开页面时的IP地址是否为`内网地址`(例如`192.168.1.2`)而不是`127.0.0.1`

试过调用python电脑的本地内网地址，也试过127.0.0.1，都不行hhh

**Comment by vvbbnn00** [comment]
在手机浏览器中能访问内网地址吗 不是二维码的那个网址 而是主页的地址

**Comment by FlanneryLong** [comment]
![image](https://user-images.githubusercontent.com/65300466/200461577-b6c82a36-3906-4427-bb9e-941cef09c404.png)

**Comment by FlanneryLong** [comment]
手机开着热点给PC的，PC只连了WIFI一个网络，没连其他
![aef344f8995f5d9a58acdf2e659ae40](https://user-images.githubusercontent.com/65300466/200461815-3e5ccb46-7f69-4d4d-9e5f-2739752db3a4.jpg)

**Comment by vvbbnn00** [comment]
试试`http://192.168.115.215:11451`是否能通过手机浏览器访问

**Comment by vvbbnn00** [comment]
开热点的那个手机可能会存在无法访问连接热点的计算机服务的情况的，可以试试换个设备，都连接在一个WiFi中

**Comment by FlanneryLong** [comment]
> 开热点的那个手机可能会存在无法访问连接热点的计算机服务的情况的，可以试试换个设备，都连接在一个WiFi中

看到页面了！！感谢感谢。刚刚找半天找不到一个别的WIFI，把防火墙全关了也不行。最后回头检查防火墙发现只关了公用的，没关专用的...我再走下一步看看

**Comment by vvbbnn00** [comment]
好的
